please run _update.py twice!